apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Daemon        off
        Flush         5
        Log_Level     error
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-azure.conf
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Docker_Mode       On
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        # Command      |  Decoder | Field | Optional Action
        # =============|==================|=================
        Decode_Field_As   escaped_utf8    log    do_next
        Decode_Field_As   escaped         log    do_next
        Decode_Field_As   json            log

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Trim      On

    [FILTER]
        Name                nest
        Match               *
        Operation           lift
        Nested_under        kubernetes
        Prefix_with         kubernetes_

    [FILTER]
        Name                nest
        Match               *
        Operation           lift
        Nested_under        kubernetes_labels
        Prefix_with         kubernetes_labels_

    [FILTER]
        Name                modify
        Match               *
        Copy                kubernetes_pod_name pod
        Copy                kubernetes_container_name container
        Copy                kubernetes_namespace_name namespace
        Copy                kubernetes_host host

    [FILTER]
        Name                record_modifier
        Match               kube.*
        Whitelist_key log
        Whitelist_key pod
        Whitelist_key container
        Whitelist_key namespace
        Whitelist_key host

    [FILTER]
        Name                grep
        Match               *
        Exclude             namespace ^((?!app|nginx-ingress|kong).)*$

  output-azure.conf: |
    [OUTPUT]
        Name        azure
        Match       *
        Customer_ID $FLUENT_AZURE_WORKSPACE_ID
        Shared_Key  $FLUENT_AZURE_WORKSPACE_KEY
